/**
 * This class file is the linear congruential rnadom number generator
 * @author Winston Zhang, wyz5rge
 *
 */
public class RandomNumberGenerator {
	public static void main(String[] arg)
	{
		System.out.println("u1 " + random(1));
		System.out.println("u2 " + random(2));
		System.out.println("u3 " + random(3));
		
		
		System.out.println("u51 " + random(51));
		System.out.println("u52 " + random(52));
		System.out.println("u53 " + random(53));
		
		System.out.println();
		
		int count = 0;
		for(int i = 1; i <= 5000; i++)
		{
			double r = random(i);
			System.out.println(r);
			if(r > 1)
				count++;
		}
		System.out.println("Count of \"large\" numbers: " + count);	// what the fuck was the bounds for then?
		
		// stress test
		for(int i = 1; i < Integer.MAX_VALUE; i++)
		{
			System.out.println(i + ": " + random(i));
		}
	}
	
	/**
	 * 
	 * @param val - subscript of u, number of iterations through recursive loop
	 * @return - u, a pseudo-random number generated by the linear congruential random number generator
	 */
	public static double random(int val)
	{
		// Parameter definitions
		double ans = 0.0;
		int i = val - 1;
		double x = 1000;	// seed
		double a = 24693;	// multiplier
		double c = 3967;	// increment
		double k = Math.pow(2, 18);	// modulus
		
		// recursion base case
		if(i == 0)
		{
			x = ((a * 1000) + c) % k;
			ans = x / k;
			return ans;
		}
		
		x = ((a * (random(val - 1) * k)) + c) % k;	// recursive call
		ans = x / k;
		return ans;
	}
}
